Repository ember-animation/ember-animated, pull requests merged in 2022-04, with the labels that each got.

#444 move `.md` files to published package
  CHANGELOG.md
  LICENSE.md
  README.md
  addon/CHANGELOG.md
  addon/LICENSE.md
  addon/README.md
Labels: documentation

#445 Remove `treePaths.addon` override
  addon/addon-main.js
  addon/package.json
  docs/ember-cli-addon-docs-4.2.2.tgz
  docs/package.json
  package.json
  pnpm-lock.yaml
  test-app/package.json
Labels: internal

#453 Fix compatibility with 0.6.1
  addon/package.json
  addon/src/components/animated-container.hbs
  addon/src/components/animated-container.ts
  pnpm-lock.yaml
  test-app/tests/integration/components/animated-container-test.js
Labels: bug

#454 Make TransitionContext type export public
  addon/src/index.ts
  addon/src/transitions/fade.ts
Labels: Feature / Enhancement

#452 Add RSVP as a peerDependency
  addon/package.json
Labels: bug

#457 Replace use of RSVP with native Promise
  addon/src/-private/concurrency-helpers.ts
  addon/src/-private/ember-scheduler.ts
  addon/src/test-support/index.js
Labels: Feature / Enhancement

#446 Simplify type checking workflow
  .github/workflows/ci.yml
  addon/babel.config.json
  addon/package.json
  addon/rollup.config.js
  package.json
  pnpm-lock.yaml
  test-app/config/ember-try-typescript.js
  test-app/package.json
Labels: internal

#459 Use angle bracket syntax for `<DocsLink>`
  docs/app/templates/docs/beacons.md
  docs/app/templates/docs/sprites.md
  docs/config/addon-docs.js
  docs/config/deploy.js
Labels: documentation

#460 run `npx ember-cli-update --to=4.3.0` to align with blueprint
  .gitignore
  addon/.gitignore
  addon/.npmignore
  addon/package.json
  docs/.ember-cli
  docs/.gitignore
  docs/README.md
  docs/app/index.html
  docs/config/ember-cli-update.json
  docs/package.json
  docs/tests/helpers/.gitkeep
  docs/tests/helpers/index.js
  docs/tests/index.html
  pnpm-lock.yaml
  test-app/.editorconfig
  test-app/.ember-cli
  test-app/.gitignore
  test-app/.template-lintrc.js
  test-app/README.md
  test-app/app/index.html
  test-app/config/ember-cli-update.json
  test-app/config/environment.js
  test-app/package.json
  test-app/tests/helpers/.gitkeep
  test-app/tests/helpers/index.js
  test-app/tests/index.html
Labels: internal

#461 Improve contributing docs
  CONTRIBUTING.md
  docs/ember-cli-build.js
  test-app/ember-cli-build.js
Labels: documentation

#458 Allow multiple beacons with the same name
  addon/src/components/animated-beacon.ts
  addon/src/services/-ea-motion.ts
  test-app/tests/integration/components/animated-beacon-test.js
Labels: bug

#462 Publish to npm from CI
  .github/workflows/ci.yml
  .github/workflows/publish-unstable.yml
  RELEASE.md
  package.json
Labels: internal

#464 feat: Update faker to use new fork.
  docs/app/adapters/person.js
  docs/package.json
  pnpm-lock.yaml
  test-app/app/adapters/person.js
  test-app/app/controllers/demos/modal.js
  test-app/package.json
Labels: dependencies
