Repository ember-animation/ember-animated, pull requests merged in 2023-11, with the labels that each got.

#619 Update docs to use and recommend inline-block
  docs/app/styles/app.scss
  docs/app/templates/docs/rules.md
Labels: documentation

#621 Bump Node.js from 16 to 18 in volta and CI configs
  .github/workflows/ci.yml
  .github/workflows/publish-unstable.yml
  .github/workflows/push-dist.yml
  docs/package.json
  package.json
  pnpm-lock.yaml
  test-app/package.json
Labels: dependencies

#623 bump TypeScript and expand CI matrix
  .github/workflows/ci.yml
  addon/package.json
  pnpm-lock.yaml
  test-app/package.json
Labels: dependencies

#624 Add 4.8 and 4.12 ember-try scenarios
  .github/workflows/ci.yml
  README.md
  test-app/config/ember-try.js
Labels: internal

#622 run `pnpm update`
  addon/package.json
  addon/src/motions/opacity.ts
  pnpm-lock.yaml
  test-app/package.json
  test-app/tests/acceptance/svg-test.js
Labels: dependencies

#625 add support for @ember/test-helpers v3
  addon/package.json
Labels: Feature / Enhancement

#626 run `pnpm update` in root
  package.json
  pnpm-lock.yaml
Labels: dependencies

#636 Include .md files in tarball
  .github/workflows/publish.yml
Labels: documentation

#637 Bump TypeScript to 5.3
  .github/workflows/ci.yml
  addon/package.json
  pnpm-lock.yaml
  test-app/package.json
Labels: dependencies

#644 Glint ember-animated/template-registry not found
  addon/package.json
Labels: bug

#648 docs: modernize docs to show class based component syntax for animated-container
  addon/src/components/animated-container.ts
Labels: documentation
