Repository ember-animation/ember-animated, pull requests merged in 2023-10, with the labels that each got.

#566 Update dependencies and fix ci
  .github/workflows/ci.yml
  .github/workflows/deploy-docs.yml
  .github/workflows/publish-unstable.yml
  addon/.eslintignore
  addon/.eslintrc.js
  addon/.prettierignore
  addon/babel.config.json
  addon/config/environment.js
  addon/package.json
  addon/rollup.config.mjs
  addon/src/-private/concurrency-helpers.ts
  addon/src/-private/ember-scheduler.ts
  addon/src/-private/margin-collapse.ts
  addon/src/-private/sprite.ts
  addon/src/-private/transform.ts
  addon/src/-private/tween.ts
  addon/src/box-shadow.ts
  addon/src/color.ts
  addon/src/components/animated-each.ts
  addon/src/motions/adjust-css.ts
  addon/src/transitions/move-over.ts
  addon/tsconfig.json
  docs/package.json
  package.json
  pnpm-lock.yaml
  test-app/app/config/environment.d.ts
  test-app/config/ember-try.js
  test-app/package.json
  test-app/tsconfig.json
  test-app/types/global.d.ts
Labels: dependencies

#608 replace publish-unstable workflow with push-dist
  .github/workflows/publish-unstable.yml
  .github/workflows/push-dist.yml
  pnpm-lock.yaml
Labels: internal

#607 remove engines.node from addon's package.json
  addon/package.json
Labels: Feature / Enhancement

#615 Widen range of ember-element-helper versions
  addon/package.json
  pnpm-lock.yaml
Labels: enhancement

#606 Fix types for modern TS
  addon/package.json
Labels: bug

#613 Introduce Glint types
  addon/package.json
  addon/src/components/animated-beacon.ts
  addon/src/components/animated-container.hbs
  addon/src/components/animated-container.ts
  addon/src/components/animated-each.ts
  addon/src/components/animated-if.ts
  addon/src/components/animated-orphans.ts
  addon/src/components/animated-value.ts
  addon/src/components/ea-list-element.ts
  addon/src/template-registry.ts
  addon/unpublished-development-types/index.d.ts
  docs/app/templates/docs/index.md
  package.json
  pnpm-lock.yaml
Labels: Feature / Enhancement
